### ISSUE TITLE
async/await

### ISSUE THREAD

**Issue by mobilegroup** [ashleydavis/promises-for-game-development#1]
I'm not an advanced C# developer, but it's been a while since I started using ES7 constructs for Javascript with different translators. I found a huge advantage to use async/await instead of Promises in many cases:
1. Code is more readable
2. The most important: gives you actual control of the flow, since all the results of previous promises are available (yeah, you can store intermediate results with promises, but it results in a terrible mess)

I miss some comments about C# async/await in the article, any reason not to rely on them?

**Comment by ashleydavis** [comment]
Unfortunately we don't have async/await in .Net 3.5
